{
    "openapi": "3.0.0",
    "info": {
        "title": "S.O.L.I.D concepts",
        "description": "Documentation for API to training SOLID concepts",
        "version": "1.0.0",
        "contact": {
            "email": "samuelmmedeiros20@gmail.com"
        }
    },
    "tags": [
        {
            "name": "users",
            "description": "User Management"
        }
    ],
    "definitions": {
        "User": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "admin": {
                    "type": "boolean"
                },
                "email": {
                    "type": "string"
                },
                "created_at": {
                    "type": "date"
                },
                "updated_at": {
                    "type": "date"
                }
            }
        }
    },
    "paths": {
        "/users": {
            "post": {
                "tags": [
                    "users"
                ],
                "summary": "Create a new user",
                "description": "Create a new user",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    },
                                    "email": {
                                        "type": "string"
                                    }
                                },
                                "example": {
                                    "name": "User name sample",
                                    "email": "Email user sample"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "id": {
                                            "type": "string"
                                        },
                                        "name": {
                                            "type": "string"
                                        },
                                        "admin": {
                                            "type": "boolean"
                                        },
                                        "email": {
                                            "type": "string"
                                        },
                                        "created_at": {
                                            "type": "date"
                                        },
                                        "updated_at": {
                                            "type": "date"
                                        }
                                    },
                                    "example": {
                                        "admin": false,
                                        "id": "03df07ec-ebd1-437e-b0da-d147e8f245dd",
                                        "name": "Samuel Medeiros",
                                        "email": "samuelmmedeiros20@gmail.com",
                                        "created_at": "2023-02-05T21:46:50.694Z",
                                        "updated_at": "2023-02-05T21:46:50.694Z"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Email is already taken",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "string"
                                        }
                                    },
                                    "example": {
                                        "error": "This email is already taken"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "tags": [
                    "users"
                ],
                "summary": "List all users",
                "description": "Only **admin** users may access",
                "parameters": [
                    {
                        "name": "user_id",
                        "in": "header",
                        "description": "user's UUID",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "id": {
                                                "type": "string"
                                            },
                                            "name": {
                                                "type": "string"
                                            },
                                            "admin": {
                                                "type": "boolean"
                                            },
                                            "email": {
                                                "type": "string"
                                            },
                                            "created_at": {
                                                "type": "date"
                                            },
                                            "updated_at": {
                                                "type": "date"
                                            }
                                        }
                                    },
                                    "example": [
                                        {
                                            "admin": false,
                                            "id": "03df07ec-ebd1-437e-b0da-d147e8f245dd",
                                            "name": "Samuel Medeiros",
                                            "email": "samuelmmedeiros20@gmail.com",
                                            "created_at": "2023-02-05T21:46:50.694Z",
                                            "updated_at": "2023-02-05T21:46:50.694Z"
                                        },
                                        {
                                            "admin": false,
                                            "id": "03df07ec-ebd1-437e-b0da-d147e8f245dd",
                                            "name": "Samuel Medeiros",
                                            "email": "samuelmmedeiros20@gmail.com",
                                            "created_at": "2023-02-05T21:46:50.694Z",
                                            "updated_at": "2023-02-05T21:46:50.694Z"
                                        }
                                    ]
                                }
                            }
                        }
                    }
                },
                "400": {
                    "description": "user is not admin or user not found",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "error": {
                                        "type": "string"
                                    }
                                },
                                "example": {
                                    "error": "User is not admin!"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/users/:user_id/admin": {
            "patch": {
                "tags": [
                    "users"
                ],
                "summary": "Turn user into admin",
                "description": "Turn an user into admin",
                "parameters": [
                    {
                        "name": "user_id",
                        "in": "path",
                        "description": "user's UUID",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "id": {
                                            "type": "string"
                                        },
                                        "name": {
                                            "type": "string"
                                        },
                                        "admin": {
                                            "type": "boolean"
                                        },
                                        "email": {
                                            "type": "string"
                                        },
                                        "created_at": {
                                            "type": "date"
                                        },
                                        "updated_at": {
                                            "type": "date"
                                        }
                                    },
                                    "example": {
                                        "admin": true,
                                        "id": "03df07ec-ebd1-437e-b0da-d147e8f245dd",
                                        "name": "Samuel Medeiros",
                                        "email": "samuelmmedeiros20@gmail.com",
                                        "created_at": "2023-02-05T21:46:50.694Z",
                                        "updated_at": "2023-02-05T21:46:50.694Z"
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Operation failed",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "string"
                                        }
                                    },
                                    "example": {
                                        "error": "User does not exist!"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/user/:user_id": {
            "get": {
                "tags": [
                    "users"
                ],
                "summary": "Show user profile",
                "description": "Show user profile info",
                "parameters": [
                    {
                        "name": "user_id",
                        "in": "path",
                        "description": "user's UUID",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "id": {
                                            "type": "string"
                                        },
                                        "name": {
                                            "type": "string"
                                        },
                                        "admin": {
                                            "type": "boolean"
                                        },
                                        "email": {
                                            "type": "string"
                                        },
                                        "created_at": {
                                            "type": "date"
                                        },
                                        "updated_at": {
                                            "type": "date"
                                        }
                                    },
                                    "example": {
                                        "admin": false,
                                        "id": "03df07ec-ebd1-437e-b0da-d147e8f245dd",
                                        "name": "Samuel Medeiros",
                                        "email": "samuelmmedeiros20@gmail.com",
                                        "created_at": "2023-02-05T21:46:50.694Z",
                                        "updated_at": "2023-02-05T21:46:50.694Z"
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "string"
                                        }
                                    },
                                    "example": {
                                        "error": "User not found"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}